export const PROCESSING_ALL_SYMBOLS = "PROCESSING_ALL_SYMBOLS";
export const GET_ALL_SYMBOLS = "GET_ALL_SYMBOLS";
export const PROCESSING_DETAIL_SYMBOL = "PROCESSING_DETAIL_SYMBOL";
export const GET_DETAIL_SYMBOL = "GET_DETAIL_SYMBOL";
export const ADD_COMMENT_TO_SYMBOL = "ADD_COMMENT_TO_SYMBOL";
export const REMOVE_COMMENT_FROM_SYMBOL = "REMOVE_COMMENT_FROM_SYMBOL";
